apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadcodb2273-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadcodb2273-tenant-component
    app.kubernetes.io/part-of: loadcodb2273-tenant-app
  name: loadcodb2273-tenant-component
  namespace: loadcodb2273-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadcodb2273-tenant-component
    weight: null
status: {}
