apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadcodb2273-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadcodb2273-tenant-component
    app.kubernetes.io/part-of: loadcodb2273-tenant-app
  name: loadcodb2273-tenant-component
  namespace: loadcodb2273-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: loadcodb2273-tenant-component
status:
  loadBalancer: {}
